spring:
  profiles:
    active: dev
  datasource:
    url:  jdbc:postgresql://localhost:5432/mall
    username: postgres
    password: 123456

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: org.wh.wpm
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    map-underscore-to-camel-case: true

